import { defineConfig } from 'tsup'
import { readTsupExternalSync } from './external-sync.mjs'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Derive tsup entry points from package.json exports field.
 * Maps each export value like "./dist/foo.js" → "src/foo.ts" (or root "foo.ts").
 * Falls back to ['src/index.ts'] if no exports or src file not found.
 */
function resolveEntryFromExports() {
  try {
    const pkgPath = join(process.cwd(), 'package.json')
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    const exportsMap = pkg.exports ?? {}
    const srcFiles = new Set()

    for (const condition of Object.values(exportsMap)) {
      // condition can be a string or { import, types, require, ... }
      const importPath = typeof condition === 'string' ? condition
        : (condition.import ?? condition.default ?? null)
      if (!importPath || typeof importPath !== 'string') continue

      // "./dist/foo.js" → "foo", then try "src/foo.ts" or "foo.ts"
      const base = importPath.replace(/^\.\/dist\//, '').replace(/\.js$/, '')
      const candidates = [`src/${base}.ts`, `${base}.ts`]
      for (const c of candidates) {
        if (existsSync(join(process.cwd(), c))) { srcFiles.add(c); break }
      }
    }

    return srcFiles.size > 0 ? Array.from(srcFiles) : ['src/index.ts']
  } catch {
    return ['src/index.ts']
  }
}

function resolveExternalDependencies() {
  try {
    const pkgPath = join(process.cwd(), 'package.json')
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    const deps = Object.keys(pkg.dependencies ?? {})
    const peerDeps = Object.keys(pkg.peerDependencies ?? {})
    return Array.from(new Set([...deps, ...peerDeps]))
  } catch {
    return []
  }
}

function getExternal() {
  // Try to use generated tsup.external.json if available
  // This file should be generated by kb-devkit-tsup-external and contains:
  // - All @kb-labs/* workspace packages (found via pnpm-workspace.yaml)
  // - All dependencies and peerDependencies from package.json
  try {
    const generated = readTsupExternalSync()
    if (generated.length > 0) {
      return generated
    }
  } catch {
    // If reading fails, fallback to package.json
  }
  // Fallback to reading package.json directly
  return resolveExternalDependencies()
}

// Pre-compute external list and entry once at module load time
const externalList = getExternal()
const entryFromExports = resolveEntryFromExports()

export default defineConfig({
  entry: entryFromExports,
  format: ['esm'],
  target: 'es2022',
  sourcemap: true,
  clean: true,
  dts: true,
  treeshake: true,
  minify: false,
  outDir: 'dist',
  splitting: false,
  skipNodeModulesBundle: true,
  shims: false,
  ignoreWatch: [
    '**/node_modules/**',
    '**/dist/**',
    '**/.git/**',
  ],
  // Mark all node_modules packages as external (including transitive deps)
  // Use noExternal: [] to prevent bundling any node_modules packages
  // This is more reliable than regex for ensuring transitive deps stay external
  noExternal: [],
  external: [
    /^[^./]|^\.[^./]|^\.\.[^/]/, // All node_modules packages (not relative paths)
    // All workspace packages from tsup.external.json (generated by kb-devkit-tsup-external)
    // This includes all @kb-labs/* packages found in pnpm-workspace.yaml
    // plus dependencies/peerDependencies from package.json
    ...externalList, // Explicitly listed packages (workspace + local deps)
    // Force all @kb-labs packages to be external
    // This catches packages linked via "link:" protocol that might not be in the workspace scan
    /^@kb-labs\//,
  ],
})
