name: Setup Node & pnpm
description: Install Node and pnpm with cache

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '20'
  package-json-path:
    description: Path to the repository package.json
    required: false
    default: 'package.json'
  fallback-pnpm-version:
    description: Fallback PNPM if packageManager is missing
    required: false
    default: '9.11.0'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Resolve PNPM version & activate via Corepack
      id: pnpm
      shell: bash
      run: |
        set -euo pipefail
        FILE="${{ inputs.package-json-path }}"
        VER=$(node -e "try{const pm=require('${FILE}').packageManager||''; const v=(pm.split('@')[1]||'').split('+')[0]; process.stdout.write(v);}catch(e){process.stdout.write('');}")
        if [ -z "$VER" ]; then VER="${{ inputs.fallback-pnpm-version }}"; fi
        echo "Using pnpm@$VER"
        corepack prepare "pnpm@$VER" --activate
        pnpm -v

    - name: Verify pnpm in PATH
      shell: bash
      run: which pnpm && pnpm -v