name: Setup Node & pnpm
description: Install Node and pnpm with cache

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '20'
  package-json-path:
    description: Path to the repository package.json
    required: false
    default: 'package.json'
  fallback-pnpm-version:
    description: Fallback pnpm version if packageManager is missing
    required: false
    default: '9.11.0'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    # read pnpm version from package.json.packageManager; if not found, use fallback
    - name: Resolve pnpm version
      id: resolve
      shell: bash
      run: |
        set -e
        FILE="${{ inputs.package-json-path }}"
        VER=$(node -e "try{const pm=require('${FILE}').packageManager||''; const v=(pm.split('@')[1]||'').split('+')[0]; process.stdout.write(v);}catch(e){process.stdout.write('');}")
        if [ -z "$VER" ]; then VER="${{ inputs.fallback-pnpm-version }}"; fi
        echo "PNPM_VERSION=$VER" >> "$GITHUB_ENV"

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - name: Verify pnpm
      shell: bash
      run: which pnpm && pnpm -v
