name: Setup Node & pnpm
description: Install Node and pnpm with cache

inputs:
  node-version:
    default: '20'
  package-json-path:
    default: 'package.json'
  fallback-pnpm-version:
    default: '9.15.0'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        # cache: pnpm   ← УДАЛИТЬ

    - name: Enable Corepack
      shell: bash
      run: |
        corepack enable
        echo "$HOME/.local/share/pnpm" >> "$GITHUB_PATH"
        echo "$HOME/.local/share/node" >> "$GITHUB_PATH"

    - name: Resolve PNPM version & activate via Corepack
      shell: bash
      run: |
        set -euo pipefail
        FILE="${{ inputs.package-json-path }}"
        VER=$(node -e "try{const pm=require('${FILE}').packageManager||''; const v=(pm.split('@')[1]||'').split('+')[0]; process.stdout.write(v);}catch(e){process.stdout.write('');}")
        [ -z "$VER" ] && VER="${{ inputs.fallback-pnpm-version }}"
        echo "Using pnpm@$VER"
        corepack prepare "pnpm@$VER" --activate
        pnpm -v

    - name: (opt) Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: (opt) Configure pnpm store
      shell: bash
      run: pnpm config set store-dir ~/.pnpm-store