name: Setup Node & pnpm
description: Install pnpm and setup Node with cache

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '20'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        package_json_path: ./package.json