name: reusable-ci-filtered

on:
  workflow_call:
    inputs:
      filter:
        description: pnpm --filter target (e.g. "--filter @kb-labs/cli")
        required: true
        type: string
      node-version:
        default: '20'
        type: string
      run-coverage:
        default: false
        type: boolean

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: KirillBaranov/kb-labs-devkit/.github/actions/setup-node-pnpm@main
        with:
          node-version: ${{ inputs['node-version'] }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm ${{ inputs.filter }} run lint
      - run: pnpm ${{ inputs.filter }} run type-check || true
      - run: pnpm ${{ inputs.filter }} run test -- --run
      - if: ${{ inputs['run-coverage'] == true }}
        run: pnpm ${{ inputs.filter }} run test:coverage
      - run: pnpm ${{ inputs.filter }} run build || true
